version: 0.0
os: linux
files:
  - source: target/ROOT.war
    destination: /opt/abvprp/apache-tomcat/webapps
  - source: target/ROOT.war
    destination: /var/lib/tomcat7/webapps
hooks:
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop.sh
      timeout: 330
      runas: root
  BeforeInstall:
    - location: scripts/removeWar.sh
      timeout: 300
      runas: root
  ValidateService:
    - location: scripts/elb/validateService.sh
      runas: root
